### ISSUE TITLE
org.whispersystems.curve25519.NoSuchProviderException

### ISSUE THREAD

**Issue by lich1011** [signalapp/libsignal-protocol-java#53]
When i use libsignal-protocol-java（version 2.7.0 ）in my android project, there is a problem. 
In my gradle file, i add dependancies like following:

          implementation'org.whispersystems:curve25519-android:0.5.0'
          implementation('org.whispersystems:signal-protocol-android:2.7.0'){
             exclude group:'org.whispersystems',module:'curve25519-android'
         }

when i directly run my project via Android sutido, the app works fine. However, when i bulid an apk, and install via the apk i had built. There is an error show up,  said “org.whispersystems.curve25519.NoSuchProviderException”

it seems like the curve25519.os not built into the apk.

**Comment by lich1011** [comment]
I found what cause the problem. It cause by android multidex setting.

**Comment by MahmoudShawky** [comment]
How did you fixed it?

**Comment by dustinsummers** [comment]
> How did you fixed it?

Add a `-keep` rule in your proguard-rules.pro file for that specific class.  (I've also seen people add it for the entire package org.whispersystems.*`)

i.e. `-keep class org.whispersystems.* {*;};`

I wouldn't advise doing the blanket one unless your OK with your app increasing in size by about 100 KB.  Otherwise, just add a specific `-keep` rule for that specific `curve25519` class.
