### ISSUE TITLE
Can I use this library with firebase database

### ISSUE THREAD

**Issue by NainalChauhan** [signalapp/libsignal-protocol-java#64]
I want to implement E2EE in a firebase chat application. Can I use this library with firebase database as server and android as a client. All the encryption and decryption will happen at client side.

**Comment by GreenApple131** [comment]
> I want to implement E2EE in a firebase chat application. Can I use this library with firebase database as server and android as a client. All the encryption and decryption will happen at client side.

Hi, did you found the answer to your question?

**Comment by NainalChauhan** [comment]
No

**Comment by ragulaust** [comment]
The forward msg count can store in the firebase

**Comment by globeedev** [comment]
can you give me the solution you having?

**Comment by NainalChauhan** [comment]
I didn't implemented the feature and didn't found any solution for that.

**Comment by jasonsaruulo** [comment]
Hey,

yes, it should be possible to use it. I do not know how you use Firebase to achieve your chat application but to achieve E2EE with this library, it is basically just about how to exchange the required keys. Your Firebase database will serve as the middle layer to store those keys and exchange among the users.

So here is what you basically have to do. Most of the steps are Firebase unrelated.

1. Implement the interfaces `SessionStore`, `PreKeyStore`, `SignedPreKeyStore` and `IdentityKeyStore`. You basically just implement how the information you create later is stored and retrieved. Make sure to create a new session in `loadSession` of `SessionStore` if there is no saved session. Another tricky part for me was the `isTrustedIdentity` function of `IdentityKeyStore`. Here you need to compare the identity key with the remote identity key of the session state if a session exists for the given address, otherwise return true.

2. On start up, each user needs to generate their identity key pair, registration id, signed pre key and some pre keys. Use the methods provided by the `KeyHelper`. It is documented in the README. The user needs to upload the public information and the device id to the server (Firebase). The device id is something you can set yourself. As far as I know the device id is meant to allow usage of multiple devices.
The library provides `serialize` methods which transform the objects into byte arrays.

`identityKeyPair.publicKey.serialize();`
`signedPreKey.serialize();`
`preKey.serialize();`
(Kotlin code)

You need to serialize each pre key. Use these byte arrays to upload the information to your server (Firebase).
The serialize methods are actually using [Google Protobuf](https://developers.google.com/protocol-buffers).

3. When user A wants to communicate with user B, he/she asks the server for the registration id, device id, iIdentity key, one of the pre keys and the signed pre key of user B (basically every public information from step 2). User A creates a new session with a pre key bundle (as shown in the README). With this session User A can create a `SessionCipher` which is able to encrypt the message (also shown in the README).
You can now again use `serialize` on the encrypted message and deliver the message to user B.

4. When user B receives the encrypted message from user A, he/she checks whether there is a session already established with user. If there is not, transform the incoming bytes to a `PreKeySignalMessage`, otherwise transform them to a `SignalMessage` (meaning just call the constructor with the bytes as argument). Create a session cipher (you do not need a pre key bundle for that) and use it to decrypt the message.

As you can see, Firebase is just involved when it comes to store and serve the public information.

3 things worth mentioning.
Each pre key is used to establish 1 session. So when the server is serving a pre key, it should remove the pre key from its list. This is also what the receiving user (in the above description user B) is doing (it is done by the library). You need to make sure that the server has some pre keys so check the number of remaining pre keys from time to time and upload new ones if needed.
For the user starting the conversation (in the above description user A), I need to call `clearUnacknowledgedPreKeyMessage` on the session state after sending the first message. Otherwise I will send pre key messages all over again (a pre key message is just needed to establish a session). I do not know whether I am doing something wrong here as I have read somewhere else that this step should not be needed.
You will come across `SignalProtocolAddress`. These are basically just identifiers. You create them with a name and a device id. Make sure that the name is unique for each user.

Hope it helps.
